#pragma once

#include "NativeGameplayTags.h"

namespace ItemSlotTags
{
	RPG005_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LeftHandWeapon)
	RPG005_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RightHandWeapon)
	RPG005_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Arrow)
	RPG005_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeadArmor)
	RPG005_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ChestArmor)
	RPG005_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gloves)
	RPG005_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Trousers)
	RPG005_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Boots)
	RPG005_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Necklace)
	RPG005_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Talisman)
	RPG005_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ring)
	RPG005_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bracelet)
}
